package syneren.qms.audit.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import syneren.qms.audit.model.AuditReport;
import syneren.qms.audit.service.AuditReportLocalServiceUtil;

/**
 * The extended model base implementation for the AuditReport service. Represents a row in the &quot;AuditReport&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AuditReportImpl}.
 * </p>
 *
 * @author anguyen
 * @see AuditReportImpl
 * @see syneren.qms.audit.model.AuditReport
 * @generated
 */
public abstract class AuditReportBaseImpl extends AuditReportModelImpl
    implements AuditReport {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a audit report model instance should use the {@link AuditReport} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            AuditReportLocalServiceUtil.addAuditReport(this);
        } else {
            AuditReportLocalServiceUtil.updateAuditReport(this);
        }
    }
}
