package syneren.qms.audit.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import syneren.qms.audit.model.AuditFinding;
import syneren.qms.audit.service.AuditFindingLocalServiceUtil;

/**
 * The extended model base implementation for the AuditFinding service. Represents a row in the &quot;AuditFinding&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AuditFindingImpl}.
 * </p>
 *
 * @author anguyen
 * @see AuditFindingImpl
 * @see syneren.qms.audit.model.AuditFinding
 * @generated
 */
public abstract class AuditFindingBaseImpl extends AuditFindingModelImpl
    implements AuditFinding {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a audit finding model instance should use the {@link AuditFinding} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            AuditFindingLocalServiceUtil.addAuditFinding(this);
        } else {
            AuditFindingLocalServiceUtil.updateAuditFinding(this);
        }
    }
}
