package syneren.qms.audit.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import syneren.qms.audit.model.CorrectiveAction;
import syneren.qms.audit.model.CorrectiveActionModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the CorrectiveAction service. Represents a row in the &quot;CorrectiveAction&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link syneren.qms.audit.model.CorrectiveActionModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CorrectiveActionImpl}.
 * </p>
 *
 * @author anguyen
 * @see CorrectiveActionImpl
 * @see syneren.qms.audit.model.CorrectiveAction
 * @see syneren.qms.audit.model.CorrectiveActionModel
 * @generated
 */
public class CorrectiveActionModelImpl extends BaseModelImpl<CorrectiveAction>
    implements CorrectiveActionModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a corrective action model instance should use the {@link syneren.qms.audit.model.CorrectiveAction} interface instead.
     */
    public static final String TABLE_NAME = "CorrectiveAction";
    public static final Object[][] TABLE_COLUMNS = {
            { "ActionId", Types.BIGINT },
            { "ActionName", Types.VARCHAR },
            { "FindingId", Types.BIGINT },
            { "Note", Types.VARCHAR },
            { "companyId", Types.BIGINT },
            { "groupId", Types.BIGINT },
            { "userId", Types.BIGINT },
            { "createDate", Types.TIMESTAMP },
            { "modifiedDate", Types.TIMESTAMP }
        };
    public static final String TABLE_SQL_CREATE = "create table CorrectiveAction (ActionId LONG not null primary key,ActionName VARCHAR(75) null,FindingId LONG,Note VARCHAR(75) null,companyId LONG,groupId LONG,userId LONG,createDate DATE null,modifiedDate DATE null)";
    public static final String TABLE_SQL_DROP = "drop table CorrectiveAction";
    public static final String ORDER_BY_JPQL = " ORDER BY correctiveAction.ActionId ASC";
    public static final String ORDER_BY_SQL = " ORDER BY CorrectiveAction.ActionId ASC";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.syneren.qms.audit.model.CorrectiveAction"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.syneren.qms.audit.model.CorrectiveAction"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.column.bitmask.enabled.syneren.qms.audit.model.CorrectiveAction"),
            true);
    public static long ACTIONID_COLUMN_BITMASK = 1L;
    public static long GROUPID_COLUMN_BITMASK = 2L;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.syneren.qms.audit.model.CorrectiveAction"));
    private static ClassLoader _classLoader = CorrectiveAction.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] {
            CorrectiveAction.class
        };
    private long _ActionId;
    private long _originalActionId;
    private boolean _setOriginalActionId;
    private String _ActionName;
    private long _FindingId;
    private String _Note;
    private long _companyId;
    private long _groupId;
    private long _originalGroupId;
    private boolean _setOriginalGroupId;
    private long _userId;
    private String _userUuid;
    private Date _createDate;
    private Date _modifiedDate;
    private long _columnBitmask;
    private CorrectiveAction _escapedModel;

    public CorrectiveActionModelImpl() {
    }

    @Override
    public long getPrimaryKey() {
        return _ActionId;
    }

    @Override
    public void setPrimaryKey(long primaryKey) {
        setActionId(primaryKey);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return _ActionId;
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Long) primaryKeyObj).longValue());
    }

    @Override
    public Class<?> getModelClass() {
        return CorrectiveAction.class;
    }

    @Override
    public String getModelClassName() {
        return CorrectiveAction.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("ActionId", getActionId());
        attributes.put("ActionName", getActionName());
        attributes.put("FindingId", getFindingId());
        attributes.put("Note", getNote());
        attributes.put("companyId", getCompanyId());
        attributes.put("groupId", getGroupId());
        attributes.put("userId", getUserId());
        attributes.put("createDate", getCreateDate());
        attributes.put("modifiedDate", getModifiedDate());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        Long ActionId = (Long) attributes.get("ActionId");

        if (ActionId != null) {
            setActionId(ActionId);
        }

        String ActionName = (String) attributes.get("ActionName");

        if (ActionName != null) {
            setActionName(ActionName);
        }

        Long FindingId = (Long) attributes.get("FindingId");

        if (FindingId != null) {
            setFindingId(FindingId);
        }

        String Note = (String) attributes.get("Note");

        if (Note != null) {
            setNote(Note);
        }

        Long companyId = (Long) attributes.get("companyId");

        if (companyId != null) {
            setCompanyId(companyId);
        }

        Long groupId = (Long) attributes.get("groupId");

        if (groupId != null) {
            setGroupId(groupId);
        }

        Long userId = (Long) attributes.get("userId");

        if (userId != null) {
            setUserId(userId);
        }

        Date createDate = (Date) attributes.get("createDate");

        if (createDate != null) {
            setCreateDate(createDate);
        }

        Date modifiedDate = (Date) attributes.get("modifiedDate");

        if (modifiedDate != null) {
            setModifiedDate(modifiedDate);
        }
    }

    @Override
    public long getActionId() {
        return _ActionId;
    }

    @Override
    public void setActionId(long ActionId) {
        _columnBitmask |= ACTIONID_COLUMN_BITMASK;

        if (!_setOriginalActionId) {
            _setOriginalActionId = true;

            _originalActionId = _ActionId;
        }

        _ActionId = ActionId;
    }

    public long getOriginalActionId() {
        return _originalActionId;
    }

    @Override
    public String getActionName() {
        if (_ActionName == null) {
            return StringPool.BLANK;
        } else {
            return _ActionName;
        }
    }

    @Override
    public void setActionName(String ActionName) {
        _ActionName = ActionName;
    }

    @Override
    public long getFindingId() {
        return _FindingId;
    }

    @Override
    public void setFindingId(long FindingId) {
        _FindingId = FindingId;
    }

    @Override
    public String getNote() {
        if (_Note == null) {
            return StringPool.BLANK;
        } else {
            return _Note;
        }
    }

    @Override
    public void setNote(String Note) {
        _Note = Note;
    }

    @Override
    public long getCompanyId() {
        return _companyId;
    }

    @Override
    public void setCompanyId(long companyId) {
        _companyId = companyId;
    }

    @Override
    public long getGroupId() {
        return _groupId;
    }

    @Override
    public void setGroupId(long groupId) {
        _columnBitmask |= GROUPID_COLUMN_BITMASK;

        if (!_setOriginalGroupId) {
            _setOriginalGroupId = true;

            _originalGroupId = _groupId;
        }

        _groupId = groupId;
    }

    public long getOriginalGroupId() {
        return _originalGroupId;
    }

    @Override
    public long getUserId() {
        return _userId;
    }

    @Override
    public void setUserId(long userId) {
        _userId = userId;
    }

    @Override
    public String getUserUuid() throws SystemException {
        return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
    }

    @Override
    public void setUserUuid(String userUuid) {
        _userUuid = userUuid;
    }

    @Override
    public Date getCreateDate() {
        return _createDate;
    }

    @Override
    public void setCreateDate(Date createDate) {
        _createDate = createDate;
    }

    @Override
    public Date getModifiedDate() {
        return _modifiedDate;
    }

    @Override
    public void setModifiedDate(Date modifiedDate) {
        _modifiedDate = modifiedDate;
    }

    public long getColumnBitmask() {
        return _columnBitmask;
    }

    @Override
    public ExpandoBridge getExpandoBridge() {
        return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
            CorrectiveAction.class.getName(), getPrimaryKey());
    }

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
        ExpandoBridge expandoBridge = getExpandoBridge();

        expandoBridge.setAttributes(serviceContext);
    }

    @Override
    public CorrectiveAction toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (CorrectiveAction) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        CorrectiveActionImpl correctiveActionImpl = new CorrectiveActionImpl();

        correctiveActionImpl.setActionId(getActionId());
        correctiveActionImpl.setActionName(getActionName());
        correctiveActionImpl.setFindingId(getFindingId());
        correctiveActionImpl.setNote(getNote());
        correctiveActionImpl.setCompanyId(getCompanyId());
        correctiveActionImpl.setGroupId(getGroupId());
        correctiveActionImpl.setUserId(getUserId());
        correctiveActionImpl.setCreateDate(getCreateDate());
        correctiveActionImpl.setModifiedDate(getModifiedDate());

        correctiveActionImpl.resetOriginalValues();

        return correctiveActionImpl;
    }

    @Override
    public int compareTo(CorrectiveAction correctiveAction) {
        long primaryKey = correctiveAction.getPrimaryKey();

        if (getPrimaryKey() < primaryKey) {
            return -1;
        } else if (getPrimaryKey() > primaryKey) {
            return 1;
        } else {
            return 0;
        }
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof CorrectiveAction)) {
            return false;
        }

        CorrectiveAction correctiveAction = (CorrectiveAction) obj;

        long primaryKey = correctiveAction.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return (int) getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
        CorrectiveActionModelImpl correctiveActionModelImpl = this;

        correctiveActionModelImpl._originalActionId = correctiveActionModelImpl._ActionId;

        correctiveActionModelImpl._setOriginalActionId = false;

        correctiveActionModelImpl._originalGroupId = correctiveActionModelImpl._groupId;

        correctiveActionModelImpl._setOriginalGroupId = false;

        correctiveActionModelImpl._columnBitmask = 0;
    }

    @Override
    public CacheModel<CorrectiveAction> toCacheModel() {
        CorrectiveActionCacheModel correctiveActionCacheModel = new CorrectiveActionCacheModel();

        correctiveActionCacheModel.ActionId = getActionId();

        correctiveActionCacheModel.ActionName = getActionName();

        String ActionName = correctiveActionCacheModel.ActionName;

        if ((ActionName != null) && (ActionName.length() == 0)) {
            correctiveActionCacheModel.ActionName = null;
        }

        correctiveActionCacheModel.FindingId = getFindingId();

        correctiveActionCacheModel.Note = getNote();

        String Note = correctiveActionCacheModel.Note;

        if ((Note != null) && (Note.length() == 0)) {
            correctiveActionCacheModel.Note = null;
        }

        correctiveActionCacheModel.companyId = getCompanyId();

        correctiveActionCacheModel.groupId = getGroupId();

        correctiveActionCacheModel.userId = getUserId();

        Date createDate = getCreateDate();

        if (createDate != null) {
            correctiveActionCacheModel.createDate = createDate.getTime();
        } else {
            correctiveActionCacheModel.createDate = Long.MIN_VALUE;
        }

        Date modifiedDate = getModifiedDate();

        if (modifiedDate != null) {
            correctiveActionCacheModel.modifiedDate = modifiedDate.getTime();
        } else {
            correctiveActionCacheModel.modifiedDate = Long.MIN_VALUE;
        }

        return correctiveActionCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(19);

        sb.append("{ActionId=");
        sb.append(getActionId());
        sb.append(", ActionName=");
        sb.append(getActionName());
        sb.append(", FindingId=");
        sb.append(getFindingId());
        sb.append(", Note=");
        sb.append(getNote());
        sb.append(", companyId=");
        sb.append(getCompanyId());
        sb.append(", groupId=");
        sb.append(getGroupId());
        sb.append(", userId=");
        sb.append(getUserId());
        sb.append(", createDate=");
        sb.append(getCreateDate());
        sb.append(", modifiedDate=");
        sb.append(getModifiedDate());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(31);

        sb.append("<model><model-name>");
        sb.append("syneren.qms.audit.model.CorrectiveAction");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>ActionId</column-name><column-value><![CDATA[");
        sb.append(getActionId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>ActionName</column-name><column-value><![CDATA[");
        sb.append(getActionName());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>FindingId</column-name><column-value><![CDATA[");
        sb.append(getFindingId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>Note</column-name><column-value><![CDATA[");
        sb.append(getNote());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>companyId</column-name><column-value><![CDATA[");
        sb.append(getCompanyId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>groupId</column-name><column-value><![CDATA[");
        sb.append(getGroupId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>userId</column-name><column-value><![CDATA[");
        sb.append(getUserId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>createDate</column-name><column-value><![CDATA[");
        sb.append(getCreateDate());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
        sb.append(getModifiedDate());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
