package syneren.qms.audit.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import syneren.qms.audit.model.CorrectiveAction;
import syneren.qms.audit.service.CorrectiveActionLocalServiceUtil;

/**
 * The extended model base implementation for the CorrectiveAction service. Represents a row in the &quot;CorrectiveAction&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CorrectiveActionImpl}.
 * </p>
 *
 * @author anguyen
 * @see CorrectiveActionImpl
 * @see syneren.qms.audit.model.CorrectiveAction
 * @generated
 */
public abstract class CorrectiveActionBaseImpl extends CorrectiveActionModelImpl
    implements CorrectiveAction {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a corrective action model instance should use the {@link CorrectiveAction} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            CorrectiveActionLocalServiceUtil.addCorrectiveAction(this);
        } else {
            CorrectiveActionLocalServiceUtil.updateCorrectiveAction(this);
        }
    }
}
