package syneren.qms.audit.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import syneren.qms.audit.model.InitAudit;
import syneren.qms.audit.service.InitAuditLocalServiceUtil;

/**
 * The extended model base implementation for the InitAudit service. Represents a row in the &quot;InitAudit&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link InitAuditImpl}.
 * </p>
 *
 * @author anguyen
 * @see InitAuditImpl
 * @see syneren.qms.audit.model.InitAudit
 * @generated
 */
public abstract class InitAuditBaseImpl extends InitAuditModelImpl
    implements InitAudit {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a init audit model instance should use the {@link InitAudit} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            InitAuditLocalServiceUtil.addInitAudit(this);
        } else {
            InitAuditLocalServiceUtil.updateInitAudit(this);
        }
    }
}
