package syneren.qms.audit.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the AuditReport service. Represents a row in the &quot;AuditReport&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link syneren.qms.audit.model.impl.AuditReportModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link syneren.qms.audit.model.impl.AuditReportImpl}.
 * </p>
 *
 * @author anguyen
 * @see AuditReport
 * @see syneren.qms.audit.model.impl.AuditReportImpl
 * @see syneren.qms.audit.model.impl.AuditReportModelImpl
 * @generated
 */
public interface AuditReportModel extends BaseModel<AuditReport> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a audit report model instance should use the {@link AuditReport} interface instead.
     */

    /**
     * Returns the primary key of this audit report.
     *
     * @return the primary key of this audit report
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this audit report.
     *
     * @param primaryKey the primary key of this audit report
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the audit ID of this audit report.
     *
     * @return the audit ID of this audit report
     */
    public long getAuditId();

    /**
     * Sets the audit ID of this audit report.
     *
     * @param AuditId the audit ID of this audit report
     */
    public void setAuditId(long AuditId);

    /**
     * Returns the audit name of this audit report.
     *
     * @return the audit name of this audit report
     */
    @AutoEscape
    public String getAuditName();

    /**
     * Sets the audit name of this audit report.
     *
     * @param AuditName the audit name of this audit report
     */
    public void setAuditName(String AuditName);

    /**
     * Returns the init audit ID of this audit report.
     *
     * @return the init audit ID of this audit report
     */
    public long getInitAuditId();

    /**
     * Sets the init audit ID of this audit report.
     *
     * @param InitAuditId the init audit ID of this audit report
     */
    public void setInitAuditId(long InitAuditId);

    /**
     * Returns the auditor of this audit report.
     *
     * @return the auditor of this audit report
     */
    @AutoEscape
    public String getAuditor();

    /**
     * Sets the auditor of this audit report.
     *
     * @param Auditor the auditor of this audit report
     */
    public void setAuditor(String Auditor);

    /**
     * Returns the note of this audit report.
     *
     * @return the note of this audit report
     */
    @AutoEscape
    public String getNote();

    /**
     * Sets the note of this audit report.
     *
     * @param Note the note of this audit report
     */
    public void setNote(String Note);

    /**
     * Returns the company ID of this audit report.
     *
     * @return the company ID of this audit report
     */
    public long getCompanyId();

    /**
     * Sets the company ID of this audit report.
     *
     * @param companyId the company ID of this audit report
     */
    public void setCompanyId(long companyId);

    /**
     * Returns the group ID of this audit report.
     *
     * @return the group ID of this audit report
     */
    public long getGroupId();

    /**
     * Sets the group ID of this audit report.
     *
     * @param groupId the group ID of this audit report
     */
    public void setGroupId(long groupId);

    /**
     * Returns the user ID of this audit report.
     *
     * @return the user ID of this audit report
     */
    public long getUserId();

    /**
     * Sets the user ID of this audit report.
     *
     * @param userId the user ID of this audit report
     */
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this audit report.
     *
     * @return the user uuid of this audit report
     * @throws SystemException if a system exception occurred
     */
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this audit report.
     *
     * @param userUuid the user uuid of this audit report
     */
    public void setUserUuid(String userUuid);

    /**
     * Returns the create date of this audit report.
     *
     * @return the create date of this audit report
     */
    public Date getCreateDate();

    /**
     * Sets the create date of this audit report.
     *
     * @param createDate the create date of this audit report
     */
    public void setCreateDate(Date createDate);

    /**
     * Returns the modified date of this audit report.
     *
     * @return the modified date of this audit report
     */
    public Date getModifiedDate();

    /**
     * Sets the modified date of this audit report.
     *
     * @param modifiedDate the modified date of this audit report
     */
    public void setModifiedDate(Date modifiedDate);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(syneren.qms.audit.model.AuditReport auditReport);

    @Override
    public int hashCode();

    @Override
    public CacheModel<syneren.qms.audit.model.AuditReport> toCacheModel();

    @Override
    public syneren.qms.audit.model.AuditReport toEscapedModel();

    @Override
    public syneren.qms.audit.model.AuditReport toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
