package syneren.qms.audit.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the AuditFinding service. Represents a row in the &quot;AuditFinding&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link syneren.qms.audit.model.impl.AuditFindingModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link syneren.qms.audit.model.impl.AuditFindingImpl}.
 * </p>
 *
 * @author anguyen
 * @see AuditFinding
 * @see syneren.qms.audit.model.impl.AuditFindingImpl
 * @see syneren.qms.audit.model.impl.AuditFindingModelImpl
 * @generated
 */
public interface AuditFindingModel extends BaseModel<AuditFinding> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a audit finding model instance should use the {@link AuditFinding} interface instead.
     */

    /**
     * Returns the primary key of this audit finding.
     *
     * @return the primary key of this audit finding
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this audit finding.
     *
     * @param primaryKey the primary key of this audit finding
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the finding ID of this audit finding.
     *
     * @return the finding ID of this audit finding
     */
    public long getFindingId();

    /**
     * Sets the finding ID of this audit finding.
     *
     * @param FindingId the finding ID of this audit finding
     */
    public void setFindingId(long FindingId);

    /**
     * Returns the finding name of this audit finding.
     *
     * @return the finding name of this audit finding
     */
    @AutoEscape
    public String getFindingName();

    /**
     * Sets the finding name of this audit finding.
     *
     * @param FindingName the finding name of this audit finding
     */
    public void setFindingName(String FindingName);

    /**
     * Returns the plan ID of this audit finding.
     *
     * @return the plan ID of this audit finding
     */
    public long getPlanId();

    /**
     * Sets the plan ID of this audit finding.
     *
     * @param PlanId the plan ID of this audit finding
     */
    public void setPlanId(long PlanId);

    /**
     * Returns the type of this audit finding.
     *
     * @return the type of this audit finding
     */
    @AutoEscape
    public String getType();

    /**
     * Sets the type of this audit finding.
     *
     * @param Type the type of this audit finding
     */
    public void setType(String Type);

    /**
     * Returns the due date of this audit finding.
     *
     * @return the due date of this audit finding
     */
    public Date getDueDate();

    /**
     * Sets the due date of this audit finding.
     *
     * @param DueDate the due date of this audit finding
     */
    public void setDueDate(Date DueDate);

    /**
     * Returns the status of this audit finding.
     *
     * @return the status of this audit finding
     */
    @AutoEscape
    public String getStatus();

    /**
     * Sets the status of this audit finding.
     *
     * @param Status the status of this audit finding
     */
    public void setStatus(String Status);

    /**
     * Returns the followup due of this audit finding.
     *
     * @return the followup due of this audit finding
     */
    public Date getFollowupDue();

    /**
     * Sets the followup due of this audit finding.
     *
     * @param FollowupDue the followup due of this audit finding
     */
    public void setFollowupDue(Date FollowupDue);

    /**
     * Returns the followup status of this audit finding.
     *
     * @return the followup status of this audit finding
     */
    @AutoEscape
    public String getFollowupStatus();

    /**
     * Sets the followup status of this audit finding.
     *
     * @param FollowupStatus the followup status of this audit finding
     */
    public void setFollowupStatus(String FollowupStatus);

    /**
     * Returns the note of this audit finding.
     *
     * @return the note of this audit finding
     */
    @AutoEscape
    public String getNote();

    /**
     * Sets the note of this audit finding.
     *
     * @param Note the note of this audit finding
     */
    public void setNote(String Note);

    /**
     * Returns the company ID of this audit finding.
     *
     * @return the company ID of this audit finding
     */
    public long getCompanyId();

    /**
     * Sets the company ID of this audit finding.
     *
     * @param companyId the company ID of this audit finding
     */
    public void setCompanyId(long companyId);

    /**
     * Returns the group ID of this audit finding.
     *
     * @return the group ID of this audit finding
     */
    public long getGroupId();

    /**
     * Sets the group ID of this audit finding.
     *
     * @param groupId the group ID of this audit finding
     */
    public void setGroupId(long groupId);

    /**
     * Returns the user ID of this audit finding.
     *
     * @return the user ID of this audit finding
     */
    public long getUserId();

    /**
     * Sets the user ID of this audit finding.
     *
     * @param userId the user ID of this audit finding
     */
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this audit finding.
     *
     * @return the user uuid of this audit finding
     * @throws SystemException if a system exception occurred
     */
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this audit finding.
     *
     * @param userUuid the user uuid of this audit finding
     */
    public void setUserUuid(String userUuid);

    /**
     * Returns the create date of this audit finding.
     *
     * @return the create date of this audit finding
     */
    public Date getCreateDate();

    /**
     * Sets the create date of this audit finding.
     *
     * @param createDate the create date of this audit finding
     */
    public void setCreateDate(Date createDate);

    /**
     * Returns the modified date of this audit finding.
     *
     * @return the modified date of this audit finding
     */
    public Date getModifiedDate();

    /**
     * Sets the modified date of this audit finding.
     *
     * @param modifiedDate the modified date of this audit finding
     */
    public void setModifiedDate(Date modifiedDate);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(syneren.qms.audit.model.AuditFinding auditFinding);

    @Override
    public int hashCode();

    @Override
    public CacheModel<syneren.qms.audit.model.AuditFinding> toCacheModel();

    @Override
    public syneren.qms.audit.model.AuditFinding toEscapedModel();

    @Override
    public syneren.qms.audit.model.AuditFinding toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
