package syneren.qms.audit.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CorrectiveAction service. Represents a row in the &quot;CorrectiveAction&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link syneren.qms.audit.model.impl.CorrectiveActionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link syneren.qms.audit.model.impl.CorrectiveActionImpl}.
 * </p>
 *
 * @author anguyen
 * @see CorrectiveAction
 * @see syneren.qms.audit.model.impl.CorrectiveActionImpl
 * @see syneren.qms.audit.model.impl.CorrectiveActionModelImpl
 * @generated
 */
public interface CorrectiveActionModel extends BaseModel<CorrectiveAction> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a corrective action model instance should use the {@link CorrectiveAction} interface instead.
     */

    /**
     * Returns the primary key of this corrective action.
     *
     * @return the primary key of this corrective action
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this corrective action.
     *
     * @param primaryKey the primary key of this corrective action
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the action ID of this corrective action.
     *
     * @return the action ID of this corrective action
     */
    public long getActionId();

    /**
     * Sets the action ID of this corrective action.
     *
     * @param ActionId the action ID of this corrective action
     */
    public void setActionId(long ActionId);

    /**
     * Returns the action name of this corrective action.
     *
     * @return the action name of this corrective action
     */
    @AutoEscape
    public String getActionName();

    /**
     * Sets the action name of this corrective action.
     *
     * @param ActionName the action name of this corrective action
     */
    public void setActionName(String ActionName);

    /**
     * Returns the finding ID of this corrective action.
     *
     * @return the finding ID of this corrective action
     */
    public long getFindingId();

    /**
     * Sets the finding ID of this corrective action.
     *
     * @param FindingId the finding ID of this corrective action
     */
    public void setFindingId(long FindingId);

    /**
     * Returns the note of this corrective action.
     *
     * @return the note of this corrective action
     */
    @AutoEscape
    public String getNote();

    /**
     * Sets the note of this corrective action.
     *
     * @param Note the note of this corrective action
     */
    public void setNote(String Note);

    /**
     * Returns the company ID of this corrective action.
     *
     * @return the company ID of this corrective action
     */
    public long getCompanyId();

    /**
     * Sets the company ID of this corrective action.
     *
     * @param companyId the company ID of this corrective action
     */
    public void setCompanyId(long companyId);

    /**
     * Returns the group ID of this corrective action.
     *
     * @return the group ID of this corrective action
     */
    public long getGroupId();

    /**
     * Sets the group ID of this corrective action.
     *
     * @param groupId the group ID of this corrective action
     */
    public void setGroupId(long groupId);

    /**
     * Returns the user ID of this corrective action.
     *
     * @return the user ID of this corrective action
     */
    public long getUserId();

    /**
     * Sets the user ID of this corrective action.
     *
     * @param userId the user ID of this corrective action
     */
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this corrective action.
     *
     * @return the user uuid of this corrective action
     * @throws SystemException if a system exception occurred
     */
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this corrective action.
     *
     * @param userUuid the user uuid of this corrective action
     */
    public void setUserUuid(String userUuid);

    /**
     * Returns the create date of this corrective action.
     *
     * @return the create date of this corrective action
     */
    public Date getCreateDate();

    /**
     * Sets the create date of this corrective action.
     *
     * @param createDate the create date of this corrective action
     */
    public void setCreateDate(Date createDate);

    /**
     * Returns the modified date of this corrective action.
     *
     * @return the modified date of this corrective action
     */
    public Date getModifiedDate();

    /**
     * Sets the modified date of this corrective action.
     *
     * @param modifiedDate the modified date of this corrective action
     */
    public void setModifiedDate(Date modifiedDate);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(
        syneren.qms.audit.model.CorrectiveAction correctiveAction);

    @Override
    public int hashCode();

    @Override
    public CacheModel<syneren.qms.audit.model.CorrectiveAction> toCacheModel();

    @Override
    public syneren.qms.audit.model.CorrectiveAction toEscapedModel();

    @Override
    public syneren.qms.audit.model.CorrectiveAction toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
