package syneren.qms.audit.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the InitAudit service. Represents a row in the &quot;InitAudit&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link syneren.qms.audit.model.impl.InitAuditModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link syneren.qms.audit.model.impl.InitAuditImpl}.
 * </p>
 *
 * @author anguyen
 * @see InitAudit
 * @see syneren.qms.audit.model.impl.InitAuditImpl
 * @see syneren.qms.audit.model.impl.InitAuditModelImpl
 * @generated
 */
public interface InitAuditModel extends BaseModel<InitAudit> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a init audit model instance should use the {@link InitAudit} interface instead.
     */

    /**
     * Returns the primary key of this init audit.
     *
     * @return the primary key of this init audit
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this init audit.
     *
     * @param primaryKey the primary key of this init audit
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the init audit ID of this init audit.
     *
     * @return the init audit ID of this init audit
     */
    public long getInitAuditId();

    /**
     * Sets the init audit ID of this init audit.
     *
     * @param InitAuditId the init audit ID of this init audit
     */
    public void setInitAuditId(long InitAuditId);

    /**
     * Returns the init audit name of this init audit.
     *
     * @return the init audit name of this init audit
     */
    @AutoEscape
    public String getInitAuditName();

    /**
     * Sets the init audit name of this init audit.
     *
     * @param InitAuditName the init audit name of this init audit
     */
    public void setInitAuditName(String InitAuditName);

    /**
     * Returns the start date of this init audit.
     *
     * @return the start date of this init audit
     */
    public Date getStartDate();

    /**
     * Sets the start date of this init audit.
     *
     * @param StartDate the start date of this init audit
     */
    public void setStartDate(Date StartDate);

    /**
     * Returns the end date of this init audit.
     *
     * @return the end date of this init audit
     */
    public Date getEndDate();

    /**
     * Sets the end date of this init audit.
     *
     * @param EndDate the end date of this init audit
     */
    public void setEndDate(Date EndDate);

    /**
     * Returns the company ID of this init audit.
     *
     * @return the company ID of this init audit
     */
    public long getCompanyId();

    /**
     * Sets the company ID of this init audit.
     *
     * @param companyId the company ID of this init audit
     */
    public void setCompanyId(long companyId);

    /**
     * Returns the group ID of this init audit.
     *
     * @return the group ID of this init audit
     */
    public long getGroupId();

    /**
     * Sets the group ID of this init audit.
     *
     * @param groupId the group ID of this init audit
     */
    public void setGroupId(long groupId);

    /**
     * Returns the user ID of this init audit.
     *
     * @return the user ID of this init audit
     */
    public long getUserId();

    /**
     * Sets the user ID of this init audit.
     *
     * @param userId the user ID of this init audit
     */
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this init audit.
     *
     * @return the user uuid of this init audit
     * @throws SystemException if a system exception occurred
     */
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this init audit.
     *
     * @param userUuid the user uuid of this init audit
     */
    public void setUserUuid(String userUuid);

    /**
     * Returns the create date of this init audit.
     *
     * @return the create date of this init audit
     */
    public Date getCreateDate();

    /**
     * Sets the create date of this init audit.
     *
     * @param createDate the create date of this init audit
     */
    public void setCreateDate(Date createDate);

    /**
     * Returns the modified date of this init audit.
     *
     * @return the modified date of this init audit
     */
    public Date getModifiedDate();

    /**
     * Sets the modified date of this init audit.
     *
     * @param modifiedDate the modified date of this init audit
     */
    public void setModifiedDate(Date modifiedDate);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(syneren.qms.audit.model.InitAudit initAudit);

    @Override
    public int hashCode();

    @Override
    public CacheModel<syneren.qms.audit.model.InitAudit> toCacheModel();

    @Override
    public syneren.qms.audit.model.InitAudit toEscapedModel();

    @Override
    public syneren.qms.audit.model.InitAudit toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
